<?php
$form = $this->form;
$form->setAttribute('action',$this->url);
$form->setAttribute('role','form');
$form->prepare();

echo $this->form()->openTag($form);

foreach ($form as $element) :
$element->setAttributes(array('class' => 'form-control',));
?>
<div class="form-group <?php if($this->formElementErrors($element))
echo "error" ?>">
<label class="control-label"><?php echo $element->getLabel() ?></label>
    <div>
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>

<?php
endforeach;
?>
<?php echo $this->form()->closeTag($form); ?>