<?php if ($this->pageCount): ?>
    <div class="paginationControl">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                    <a href="<?php echo $this->url($this->route); ?><?php echo $this->previous; ?>/<?php echo $this->order; ?>">
                        <<
                    </a>
            <?php else: ?>
                    <a href="#">
                        <<
                    </a>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?> 
                        <a href="<?php echo $this->url($this->route);?><?php echo $page; ?>/<?php echo $this->order; ?>">
                            <?php echo $page; ?>
                        </a>
                <?php else: ?>
                        <?php echo $page; ?>
                <?php endif; ?>
                
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                    <a href="<?php echo $this->url($this->route); ?><?php echo $this->next; ?>/<?php echo $this->order; ?>">
                        >>
                    </a>
            <?php else: ?>
                    <a href="#">
                        >>
                    </a>

            <?php endif; ?>

    </div>
<?php endif; ?>