<?php
$title = 'Report a new obstruction';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$this->form($form,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
$form->setAttribute('action', $this->url('reporting', array('action' => 'add')));


$form->setAttribute('action', $this->url('reporting', array('action' => 'add')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>

