<?php
$title = 'Edit an obstruction reporting';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'reporting',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->setAttribute('role','form');

echo $this->partial('partial/form-partial', array(
		'form' => $this->form,
'url' =>  $this->url('whatever', array('action' => 'add')))); ?>
?>



<!--  
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Obstruction'); ?> :</h3>
            </div>
            <div class="panel-body">
-->
		      	<?php $form->prepare(); ?>
			  	<?php echo $this->form()->openTag($form); ?>
		        <?php
							echo "<br />".$this->formHidden($form->get('id'));
				?>
				<div class="form-group">
				<?php	    echo "<br />".$this->formRow($form->get('x'),'prepend'); ?>
				</div>
				<?php		echo "<br />".$this->formRow($form->get('y'));
							echo "<br />".$this->formRow($form->get('feature'));
							echo "<br />".$this->formRow($form->get('type'));
							echo "<br />".$this->formRow($form->get('name'));
							echo "<br />".$this->formRow($form->get('location_info'));
							echo "<br />".$this->formRow($form->get('fishpass'));
							echo "<br />".$this->formRow($form->get('fishpasstype'));
							echo "<br />".$this->formRow($form->get('fishpass_info'));
							echo "<br />".$this->formRow($form->get('porosity_sal'));
				?>		        	
		        <?php 
							echo "<br />".$this->formRow($form->get('porosity_trout'));
							echo "<br />".$this->formRow($form->get('porosity_gray'));
							echo "<br />".$this->formRow($form->get('porosity_rlamp'));
							echo "<br />".$this->formRow($form->get('porosity_slamp'));
							echo "<br />".$this->formRow($form->get('porosity_eel'));
							echo "<br />".$this->formRow($form->get('porosity_cyp'));
							echo "<br />".$this->formRow($form->get('porosity_judgement'));
							echo "<br />".$this->formRow($form->get('local_head_drop'));
							echo "<br />".$this->formRow($form->get('porosity_info'));
							echo "<br />".$this->formRow($form->get('file_name'));
							echo "<br />".$this->formSubmit($form->get('submit'));
							?>

		        <?php  echo $this->form()->closeTag(); ?>

		        			<?php 
							if ($this->escapeHtml($form->get('file_name')->getValue()) == "") { ?>
								::no image::
							<?php } else { ?>
								<a href="<?php echo $this->basePath() . '/obstructions/' . $this->escapeHtml($form->get('file_name')->getValue());?>" target="_blank">
									<img style="max-width:400px;" src="<?php echo $this->basePath() . '/obstructions/' . $this->escapeHtml($form->get('file_name')->getValue());?>" />
								</a>
							<?php } ?>
		   
		        
		        <!--  
		      </div>
			</div>
			-->
			
			
<form role="form">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>