<?php
$title = 'Edit an obstruction reporting';
$this->headTitle ( $title );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$this->form($form,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);



$form->setAttribute('action', $this->url(
    'reporting',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>


<?php
if ($this->escapeHtml ( $form->get ( 'file_name' )->getValue () ) == "") {
	?>
	::no image::
<?php } else { ?>
<a
	href="<?php echo $this->basePath() . '/obstructions/' . $this->escapeHtml($form->get('file_name')->getValue());?>"
	target="_blank"> <img style="max-width: 400px;"
	src="<?php echo $this->basePath() . '/obstructions/' . $this->escapeHtml($form->get('file_name')->getValue());?>" />
</a>
<?php } ?>
		   
		        
