<div class="jumbotron">
    <h1>Welcome to the waterway obstructions simple web interface</h1>
</div>

<div class="row">

    <div class="col">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Waterway obstructions') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                	Waterways such as rivers and canals are an indication of the health of our environment and provide us with livelihoods, leisure time and power opportunities.
				</p><p>
					We have catalogued over 26,000 physical obstructions on the river network of England and Wales. These include weirs, dams, barrages, locks and waterfalls. Around 18,000 are artificial, manmade structures. These can and do have a direct impact on the ecological status of our rivers by interfering with ecological processes like sediment transport and fish movement. They also have an impact on our leisure time, angling and canoeing for example, which are large participation activities.
				</p><p>
					River obstructions are a particular problem where they prevent or hinder the migration of fish, particularly salmon, trout, lamprey and eel. The population of eel in UK rivers has declined by 95% from 40 years ago due in large part to river obstructions.
				</p><p>
					http://www.environment-agency.gov.uk/research/library/consultations/109501.aspx.
				</p><p>
					It is recognised that the installation of fish passes across the country will be necessary on a significant scale for us to improve the free movement of fish, improve the ecology of our rivers and to comply with our legislative obligations. But fish passes are expensive and solutions need to be prioritised and our resources focused where they are most needed.
				</p><p>
					River obstructions aren t just an issue for river ecology.  They have an impact on the local economy and leisure facilities of the community. Anglers, canoeists and walkers all have an interest in knowing where obstructions are and in knowing relevant information about them such as size, height etc , albeit for differing reasons. Sometimes solutions to river obstruction problems can come together and facilities to pass fish have also been designed for navigation purposes such as canoe friendly bristle passes which are good for fish.
				</p><p>
					This App is needed to ensure we have the right information that can be used and accessed by anyone with an interest in our river systems and that we can use to prioritise solutions and highlight multi-purpose usage. It will do this by adding to our obstructions catalogue and wising up existing barriers with local on site information.
				</p><p>
					The Environment Agency has a dataset of approximately 26k obstructions on watercourses but this may be the tip of the iceberg in terms of obstructions that have impacts on our water environment.
				</p>
			</div>
        </div>
    </div>
</div>
